language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: SRlyY5g7vTbTkddt4ohYFt2l3nkSM/lpExhcWfnBj/IpDE4ynaoSu5CGidwr/Xp5xAUzN8TgdwU2rjtyJFDeDAn9I3UXUtbkTkCB1N/g+7svv/m9J/3jFYCEclEmv3hzdBYJgDgHgh6od6Y5Jl1JDOVmraj+7xHju74WQ2v0halh5yRo3Ghuxdf4hZcjGsgoXbb+fBTaYs5gND905S/OE/RwdCON9N8Kjb71CiXmfDFIaPHc0F6jL183sfRzXnFtDrbJSGiDvA3s+AzAjVOmCbtjVo9o4BwCqVzDC0ROcOpDuLLQ72b6BWBZ5o1UtUTiKNgmTPSZyuHQZMN6bl78w6xizDmg3guoyo6/+ntOSjtNj0LQZJQAeS0nS14qevz+VbPTo0ju1KiLcZ9rQZOAIyARQxtTYzboNi8ax725b8Gu5bcPz1/hXrBbqqG38iLWWBrp2OXKMAwIcaSA1+r8EamH/SuzBI7Xyi3QGT8qR6m6r1EvxDs270+capr4GPT/JDXXEUyAeH2zmPSBW0acKqfoYQVARgBU2afs5w2Os+s74NYrFLoq3rQs1BvOD09O0qhy2Xvad1UEMxvOpbl6oFllPLYgL6RRURugOqqT+Da0/ZhS5Jr6klgr/8fxieegRHdlFtA30Vee/Q1QccOw/o+L0DqHHZprU51bNwHDg/4=
  file:
    - "hast-util-is-element.js"
    - "hast-util-is-element.min.js"
  on:
    tags: true
