language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: eSsk7MN9PGXfXZxBAT/uD+tMPqqsBDE6mpTVZMfzeGnugZSy2f72JTIRrN5VI0AlWb3pxBt7ezF5QFOs/h+cFYoLPgbgtROac2ToLGS033j9b6XUNjBDn/fRdDLCrcYmVkHZsoW+F0Fk9ErmN8R1IdK+uMOEqM+/3SodH75teCCeao23nuNjuFeLkKT4ZshNMFjfC+gVSkblvcNHOr5OlAdQrpzpSyBxyT5KsfNzbJgPD1l3PzNsfJu1KWlghoysx04iiuWzF81ykhI3MGg2ancygXj2MhJQg3njt+8KoI5ts+Ufp/4GWxH217wGVFMPH/bCD7WKJWeI/e60ZqDJrO1VwPOFF/xisldKKSyRAf8oYL2Es6jntWG1yHb/HxydTP/j/vm8MrzS+dVG1DUUZwB/Ya6ze/qLNEdbOOUHF8meaG/nL09iJXDEf2jjRNcvAMGvXv54Qzqme8Z/PmAEbIlEaFwRtkXS6ysbMXhV7CTkkQ4q8BpjnV+gB5kCh34iCEM5m8zkv/m+dIIl6HmmPpQBlfN6mEk241pfe96ypDAeZSjC/6o62sQJlF79xDH00LpjRCJBsk+ZOEsgCQ8/2ocTSyxtZX5SD04GluPqkjSdDnYnNun8Nh1O3X5eT/TJsu2HWreTA52L6wbc0fflLR+RXzcgts34Mug3L8heCrI=
  file:
    - "hast-util-is-element.js"
    - "hast-util-is-element.min.js"
  on:
    tags: true
